channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.1.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.13.1
name: mlflow-env
